# Generated by Django 5.2.6 on 2025-11-11 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0007_alter_businessregistration_id_document_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('invoice_paid', 'Invoice Paid'), ('invoice_overdue', 'Invoice Overdue'), ('payment_received', 'Payment Received'), ('payment_reminder', 'Payment Reminder'), ('low_cash', 'Low Cash Alert'), ('transaction_added', 'Transaction Added'), ('recurring_invoice', 'Recurring Invoice Generated'), ('mpesa_payment', 'M-Pesa Payment'), ('system', 'System Notification'), ('alert', 'Alert'), ('info', 'Information')], default='info', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at', 'is_read'], name='core_notifi_user_id_9157dc_idx'), models.Index(fields=['business', '-created_at'], name='core_notifi_busines_a2b325_idx'), models.Index(fields=['notification_type', '-created_at'], name='core_notifi_notific_38b6f7_idx')],
            },
        ),
    ]
